src/objects/Card__c.object
<CustomObject>
    <fields>
        <fullName>Shop_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shop Product</label>
        <referenceTo>Shop_Product__c</referenceTo>
        <relationshipLabel>Cards</relationshipLabel>
        <relationshipName>Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Value__c</fullName>
        <label>Total Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Sold__c</fullName>
        <label>Unit Sold</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Card</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Category__c.object
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Product Junctions</relationshipLabel>
        <relationshipName>Product_Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Shop_Product__c</fullName>
        <label>Shop Product</label>
        <referenceTo>Shop_Product__c</referenceTo>
        <relationshipLabel>Product Junctions</relationshipLabel>
        <relationshipName>Product_Junctions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Product Junction</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Product Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Shop_Product__c.object
<CustomObject>
    <description>Object for the Product Catalog project</description>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Inventory__c</fullName>
        <label>Inventory</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Shop Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestShopController.cls
@IsTest
public class TestShopController {

    static Category__c category = new Category__c(name='category');

    static Product_Junction__c productJunction = new Product_Junction__c();

    static List<Product_Junction__c> productJunctions = new List<Product_Junction__c>();

    static Map<String, List<Product_Junction__c>> pj = new Map<String, List<Product_Junction__c>>();

    static List<cCard> cards = new List<cCard>();

    @isTest static void InsertCategoryProductCardCompareGetCardsAndGetProductsMethodsWithNull() {
        Shop_Product__c product = new Shop_Product__c(Name='product', Price__c=10, Inventory__c=30);
        Card__c card = new Card__c(Unit_Sold__c=2, Total_Value__c=100);

        Test.startTest();
        insert product;
        insert category;
        productJunction.Shop_Product__c = product.Id;
        productJunction.Category__c = category.id;
        insert productJunction;
        card.Shop_Product__c = product.Id;
        insert  card;
        shopController shopController = new shopController();
        System.assertNotEquals(null, shopController.getProductsByCategories());
        System.assertNotEquals(null, shopController.getCards());
        Test.stopTest();
    }

    @isTest static void InsertCategoryProductAddToCardCompareCardsWithNull() {
        Test.startTest();
        insert category;
        Shop_Product__c product = new Shop_Product__c(Name='product', Price__c=10, Inventory__c=10, Count__c=1);
        insert product;
        productJunction.Shop_Product__r = product;
        productJunction.Category__r = category;
        productJunctions.add(productJunction);
        pj.put(category.Name, productJunctions);
        shopController shopController = new shopController();
        shopController.productsList = pj;
        shopController.addToCard();
        System.assertNotEquals(new List<Card__c>(), [SELECT id FROM Card__c LIMIT 1]);
        Test.stopTest();
    }

    @isTest static void addCardWithSurplusInventoryLimitCompareCardsWithNull() {
        Test.startTest();
        insert category;
        Shop_Product__c product = new Shop_Product__c(Name='product', Price__c=10, Inventory__c=1, Count__c=10);
        insert product;
        productJunction.Shop_Product__r = product;
        productJunction.Category__r = category;
        productJunctions.add(productJunction);
        pj.put(category.Name, productJunctions);
        shopController shopController = new shopController();
        shopController.productsList = pj;
        shopController.addToCard();
        System.assertEquals(new List<Card__c>(), [SELECT id FROM Card__c LIMIT 1]);
        Test.stopTest();
    }

    @isTest static void addCardWithSurplusProductLimitCompareCardsWithNull() {
        Test.startTest();
        insert category;
        Shop_Product__c product = new Shop_Product__c(Name='product', Price__c=10, Inventory__c=200, Count__c=100);
        insert product;
        productJunction.Shop_Product__r = product;
        productJunction.Category__r = category;
        productJunctions.add(productJunction);
        pj.put(category.Name, productJunctions);
        shopController shopController = new shopController();
        shopController.productsList = pj;
        shopController.addToCard();
        System.assertEquals(new List<Card__c>(), [SELECT id FROM Card__c LIMIT 1]);
        Test.stopTest();
    }

    @isTest static void InsertCategoryProductCardRemoveCardCompareCardsWithNull() {

        Test.startTest();
        insert category;
        Shop_Product__c product = new Shop_Product__c(Name='product', Price__c=10, Inventory__c=10, Count__c=1);
        insert product;
        productJunction.Shop_Product__r = product;
        productJunction.Category__r = category;
        Card__c card = new Card__c(Unit_Sold__c=2, Total_Value__c=3000);
        card.Shop_Product__r = product;
        insert  card;
        cCard cCard = new cCard(card);
        cCard.selected = true;
        cards.add(cCard);
        shopController shopController = new shopController();
        shopController.cardsList = cards;
        shopController.removeSelected();
        System.assertEquals(new List<Card__c>(), [SELECT id FROM Card__c LIMIT 1]);
        Test.stopTest();
    }

    @isTest static void InsertCategoryProductCardSubmitCardCompareCardsWithNull() {
        Shop_Product__c product = new Shop_Product__c(Name='product', Price__c=10, Inventory__c=10, Count__c=1);
        Card__c card = new Card__c(Unit_Sold__c=2, Total_Value__c=3000);
        Card__c card1 = new Card__c(Unit_Sold__c=2, Total_Value__c=700);

        Test.startTest();
        insert product;
        insert category;
        productJunction.Shop_Product__c = product.Id;
        productJunction.Category__c = category.id;
        insert productJunction;
        card.Shop_Product__c = product.Id;
        insert  card;
        insert card1;
        cCard cCard = new cCard(card);
        cCard.selected = true;
        cCard cCard1 = new cCard(card1);
        cCard1.selected = true;
        cards.add(cCard);
        cards.add(cCard1);
        shopController shopController = new shopController();
        shopController.cardsList = cards;
        shopController.submitSelected();
        System.assertEquals(new List<Card__c>(), [SELECT id FROM Card__c WHERE Status__c = 'Open' LIMIT 1]);
        Test.stopTest();
    }

    @isTest static void compareOrdersLinkWithConstant() {
        shopController shopController = new shopController();
        String link = shopController.goOrders().getUrl();
        System.assertEquals(ShopConstants.ORDERS_LINK, link);
    }

}