src/objects/Card__c.object
<CustomObject>
    <fields>
        <fullName>Shop_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shop Order</label>
        <referenceTo>Shop_Order__c</referenceTo>
        <relationshipLabel>Cards</relationshipLabel>
        <relationshipName>Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Value__c</fullName>
        <label>Total Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Sold__c</fullName>
        <label>Unit Sold</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Card</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shop_Order__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Value__c</fullName>
        <label>Total Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unit Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Shop Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Shop Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shop Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestOrderControllerClass.cls
@IsTest
public class TestOrderControllerClass {

    @isTest static void InsertCardAndOrderCompareGetOrderMethodWithNull() {
        List<Card__c> cards = new List<Card__c>();
        Shop_Order__c order = new Shop_Order__c(Status__c = 'Closed');

        Test.startTest();
        insert order;
        Card__c card = new Card__c(Total_Value__c = 100, Unit_Sold__c = 2, Status__c = 'Closed');
        card.Shop_Order__r = order;
        cards.add(card);
        insert cards;
        orderController controller = new orderController();
        System.assertNotEquals(null, controller.getOrders());
        Test.stopTest();

    }

    @isTest static void compareGoShopLinkWithConstant() {
        orderController controller = new orderController();
        String link = controller.goShop().getUrl();
        System.assertEquals(ShopConstants.SHOP_LINK, link);
    }

}