src/objects/Card__c.object
<CustomObject>
    <fields>
        <fullName>Created__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Shop_Order__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shop Order</label>
        <referenceTo>Shop_Order__c</referenceTo>
        <relationshipLabel>Cards</relationshipLabel>
        <relationshipName>Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Shop_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Shop Product</label>
        <referenceTo>Shop_Product__c</referenceTo>
        <relationshipLabel>Cards</relationshipLabel>
        <relationshipName>Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Value__c</fullName>
        <label>Total Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Sold__c</fullName>
        <label>Unit Sold</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Card</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shop_Order__c.object
<CustomObject>
    <fields>
        <fullName>Created__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Created</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Value__c</fullName>
        <label>Total Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Sold__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unit Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Shop Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Shop Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shop Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shop_Product__c.object
<CustomObject>
    <description>Object for the Product Catalog project</description>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Shop Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shop Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderController.cls
public class OrderController {

    private String usedId = UserInfo.getUserId();

    private List<Shop_Order__c> ordersList = [SELECT id, name, Status__c
                                              FROM Shop_Order__c
                                              WHERE OwnerId =:usedId
                                              LIMIT 50];

    private Map<String, List<Card__c>> orderMap {get; set;}

    public Map<String, List<Card__c>> getOrders() {

        orderMap = new Map<String, List<Card__c>>();

        for (Shop_Order__c order: ordersList) {

            List<Card__c> cards = [SELECT Shop_Product__r.Name,
                                   Shop_Product__r.Price__c, 
                                   Unit_Sold__c, 
                                   Total_Value__c, 
                                   Created__c,
                    			   Shop_Order__r.Status__c, 
                                   Shop_Order__r.Total_Value__c 
                                   FROM Card__c
                                   WHERE Shop_Order__r.id =:order.Id
                                   AND Status__c =:ShopConstants.CLOSED_STATUS
                                   LIMIT 20];
            orderMap.put(order.Name, cards);
        }
        
        return orderMap;
    }

    public PageReference goShop() {
        PageReference shopURL = new PageReference(ShopConstants.SHOP_LINK);
        shopURL.setRedirect(true);

        return shopURL;
    }

}